version: '3'
services:
  apis_nv:
    image: node:16.15.0
    container_name: nv_node
    hostname: nv_node
    ports:
      - 3333:3333

    restart: unless-stopped
    volumes:
      - .:/app
    tty: true
    working_dir: /app
  
  db_nv:
    image: postgres
    container_name: "nv_postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: valente
    ports:
      - 5432:5432
    
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
